version: "3.9"

services:
  autoscaler:
    image: jcwimer/docker-swarm-autoscaler
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
