version: "3.9"

services:
  autoscaler:
    image: aryanbariya/my-autoscaler:latest   # your custom autoscaler image
    environment:
      - PROMETHEUS_URL=http://monitoring_prometheus:9090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - next-network
    deploy:
      replicas: 1

networks:
  next-network:
    external: true
