apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: next-app-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: next-app

  minReplicaCount: 1
  maxReplicaCount: 20

  pollingInterval: 10
  cooldownPeriod: 20

  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        metricName: next_cpu_usage
        query: |
          sum(rate(container_cpu_usage_seconds_total{pod=~"next-app.*"}[1m]))
        threshold: "0.05"  

    - type: prometheus
      metadata:
        serverAddress: http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        metricName: next_memory_usage
        query: |
          sum(container_memory_usage_bytes{pod=~"next-app.*"})
        threshold: "200000000"   # 200 MB

    - type: prometheus
      metadata:
        serverAddress: http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        metricName: next_request_rate
        query: |
          sum(rate(nginx_ingress_controller_requests{ingress="next-app-ingress"}[30s]))
        threshold: "10"     # 10 requests / second


    # - type: cron
    #   metadata:
    #     timezone: "Asia/Kolkata"
    #     start: "57 9 * * *"   # 9:55 AM
    #     end: "58 9 * * *"     # 9:57 AM
    #     desiredReplicas: "5"
    
