version: "3.9"

services:
  next-app:
    image: aryanbariya/next-app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://root:Aryan%401234@next-app_mysql:3306/mydb"
      MONGODB_URI: "mongodb://next-app_mongo:27017/school"
    depends_on:
      - mysql
      - mongo
    networks:
      - next-network

  mongo:
    image: mongo:6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongo-data:/data/db
    networks:
      - next-network

  mysql:
    image: mysql:8
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "Aryan@1234"
      MYSQL_DATABASE: "mydb"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - next-network

volumes:
  mongo-data:
  mysql-data:

networks:
  next-network:
    driver: overlay
