version: "3.9"

services:
  next-app:
    image: aryanbariya/next-app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://next-app_mongo:27017/school"
    depends_on:
      - mysql
      - mongo
    networks:
      - next-network

  mongo:
    image: mongo:6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongo-data:/data/db
    networks:
      - next-network


volumes:
  mongo-data:

networks:
  next-network:
    driver: overlay
