version: "3.9"

services:
  next-app:
    image: aryanbariya/next-app:latest
    labels:
       swarm.autoscaler: "true"
       swarm.autoscaler.minimum: "2"
       swarm.autoscaler.maximum: "8"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      MONGODB_URI: "mongodb://mongo:27017/school"
    networks:
      - next-network

  mongo:
    image: mongo:6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongo-data:/data/db
    networks:
      - next-network

  haproxy:
    image: haproxy:latest
    ports:
    - target: 80
      published: 8085
      protocol: tcp
      mode: host

    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - next-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  autoscaler:
    image: aryanbariya/my-autoscaler:latest  # your custom autoscaler image
    environment:
      - PROMETHEUS_URL=http://monitoring_prometheus:9090
      - CPU_PERCENTAGE_UPPER_LIMIT=10
      - CPU_PERCENTAGE_LOWER_LIMIT=5
      - SLEEP_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # needed to scale services
    networks:
      - next-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
volumes:
  mongo-data:

networks:
  next-network:
    driver: overlay
