version: "3.9"

services:
  next-app:
    image: aryanbariya/next-app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      MONGODB_URI: "mongodb://mongo:27017/school"
    networks:
      - next-network

  mongo:
    image: mongo:6
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mongo-data:/data/db
    networks:
      - next-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"       
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - next-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  mongo-data:

networks:
  next-network:
    driver: overlay
